DROP TABLE PROJECT_BUILD_STATUS;

DROP TABLE BUILD_HISTORY;

CREATE TABLE PROJECT_BUILD_STATUS(ID INT(11),PRODUCT VARCHAR(30),DEV VARCHAR(80),QA VARCHAR(80),STAGE VARCHAR(80),PROD VARCHAR(80));

CREATE TABLE BUILD_HISTORY(BUILD_ID INT(11),BUILD_TIER VARCHAR(10),BUILD_STATUS VARCHAR(10),LAST_BUILD_TIME DATETIME,WIKI_BUILD_STATUS VARCHAR(4),PRODUCT VARCHAR(20));
