DROP TABLE IF EXISTS PROJECT_CERTIFICATION_STATUS;

CREATE TABLE PROJECT_CERTIFICATION_STATUS(ID INT(11), PRODUCT VARCHAR(500), CERTIFICATION_STATUS VARCHAR(500), SINGLE_COMMAND_BUILD VARCHAR(500), SINGLE_COMMAND_DEPLOYMENT VARCHAR(500), REMOTE_UPGRADE VARCHAR(500), DATABASE_INTEGRATION VARCHAR(500), TEMPLATE_VALIDATION VARCHAR(500), PRIVATE_PROPERTIES VARCHAR(500), CI_BUILD VARCHAR(500), DEPLOYMENT_SHAKEOUT VARCHAR(500), BDA_ENABLED VARCHAR(500), COMMANDLINE_INSTALLER VARCHAR(500), REMOTE_UPGRADE VARCHAR(500));

