DROP TABLE PROJECT_BUILD_STATUS;

DROP TABLE BUILD_HISTORY;

CREATE TABLE PROJECT_CERTIFICATION_STATUS(ID INT(11),PRODUCT VARCHAR(30),CERTIFICATION_STATUS VARCHAR(30), CERTIFICATION_WIKI_STATUS VARCHAR(30), SINGLE_COMMAND_BUILD VARCHAR(80),SINGLE_COMMAND_DEPLOYMENT VARCHAR(80),DATABASE_INTEGRATION VARCHAR(80));

CREATE TABLE BUILD_CERTIFICATION_HISTORY(ID INT(11),PRODUCT VARCHAR(30),SINGLE_COMMAND_BUILD VARCHAR(80),SINGLE_COMMAND_DEPLOYMENT VARCHAR(80),DATABASE_INTEGRATION VARCHAR(80),LAST_BUILD_TIME DATETIME);
