DROP TABLE PROJECT_CERTIFICATION_STATUS;

CREATE TABLE PROJECT_CERTIFICATION_STATUS(ID INT(11),PRODUCT VARCHAR(30),CERTIFICATION_STATUS VARCHAR(30), SINGLE_COMMAND_BUILD VARCHAR(80),SINGLE_COMMAND_DEPLOYMENT VARCHAR(80),DATABASE_INTEGRATION VARCHAR(80), PRIVATE_PROPERTIES VARCHAR(80));

