INSERT INTO project_poc VALUES( 'BioPortal','TBD','TBD' ,'Frank Hartel',  'hartel@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caAdapter','Eugene Wang','wangeug@mail.nih.gov','Sichen Liu','liusi@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caBIO - DB','Jim Sun','sunj2@mail.nih.gov','Juli Klemm','klemmj@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caBIO - Grid Service','Jim Sun','sunj2@mail.nih.gov','Juli Klemm','klemmj@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caBIO - Web App','Jim Sun','sunj2@mail.nih.gov','Juli Klemm','klemmj@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caBIO DB automation','Jim Sun','sunj2@mail.nih.gov','Juli Klemm','klemmj@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caCore SDK WorkBench','Satish Patel','patelsat@mail.nih.gov','Sichen Liu','liusi@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caCore','Satish Patel','patelsat@mail.nih.gov','Sichen Liu','liusi@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - Admin Tool','Raghu Chintalapati','chintalr@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - caDSR API','Raghu Chintalapati','chintalr@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - caDSR Sentinel','Raghu Chintalapati','chintalr@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - cdeBrowser','Raghu Chintalapati','chintalr@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - cdeCurate','Raghu Chintalapati','chintalr@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - Formbuilder','Raghu Chintalapati','chintalr@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - Freestyle','Raghu Chintalapati','chintalr@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - Object Cart API','Denis Avdic','avdicd@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - SIW','Raghu Chintalapati','chintalr@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caDSR - UML Model Browser','Raghu Chintalapati','chintalr@mail.nih.gov','Dave Hau','haudt@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caGrid','John Eisenschmidt','eisenschmidtjw@mail.nih.gov','Avinash Shanbhag','shanbhak@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caMOD','Maki Duncan','duncanmk@mail.nih.gov','Juli Klemm','klemmj@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caNanoLab','Sue Pan','pansu@mail.nih.gov','Anand Basu','basuan@mail.nih.gov');
INSERT INTO project_poc VALUES( 'caTissue','Michelle Lee','leeml@mail.nih.gov','Ian Fore','forei@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CCTS - C3PR','Ram Chilkur','chilukurir2@mail.nih.gov','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CCTS - caAERS','Ram Chilkur','chilukurir2@mail.nih.gov','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CCTS - caXchange','Ram Chilkur','chilukurir2@mail.nih.gov','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CCTS - LabViewer','Ram Chilkur','chilukurir2@mail.nih.gov','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CCTS - PSC','Ram Chilkur','chilukurir2@mail.nih.gov','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CCTS - Suite','Ram Chilkur','chilukurir2@mail.nih.gov','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CDS','TBD',' ','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'COPPA - CTRP - Accrual','Edmond Mulaire','edmond.mulaire@semanticbits.com','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'COPPA - PA','Edmond Mulaire','edmond.mulaire@semanticbits.com','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'COPPA - PO','Edmond Mulaire','edmond.mulaire@semanticbits.com','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CPAS','Denny Chan','dc331z@nih.gov','Carl Schaefer','cs339h@nih.gov');
INSERT INTO project_poc VALUES( 'CSM - CGMWeb','Raghu Chintalapati','chintalr@mail.nih.gov','Sichen Liu','liusi@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CSM - LLT','Satish Patel','patelsat@mail.nih.gov','Sichen Liu','liusi@mail.nih.gov');
INSERT INTO project_poc VALUES( 'CSM - UPT','Satish Patel','patelsat@mail.nih.gov','Sichen Liu','liusi@mail.nih.gov');
INSERT INTO project_poc VALUES( 'GenePattern','TBD',' ','Juli Klemm','klemmj@mail.nih.gov');
INSERT INTO project_poc VALUES( 'I-SPY','Shine Jacobs','jacobss2@mail.nih.gov','Anand Basu','basuan@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LexEVS - DB','Raghu Chintalapati','chintalr@mail.nih.gov','Frank Hartel','hartel@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LexEVS - NCI Report Writer','Jason Lucas','jason.lucas@ngc.com','Frank Hartel','hartel@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LexEVS - NCIT Browser','Raghu Chintalapati','chintalr@mail.nih.gov','Frank Hartel','hartel@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LexEVS - Protoge','Raghu Chintalapati','chintalr@mail.nih.gov','Frank Hartel','hartel@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LexEVS - Web App','Raghu Chintalapati','chintalr@mail.nih.gov','Frank Hartel','hartel@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LexEVS DB Automation','Raghu Chintalapati','chintalr@mail.nih.gov','Frank Hartel','hartel@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LSD - caB2B','Chris Piepenbring','piepenbringc@mail.nih.gov','Anand Basu','basuan@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LSD - caGWAS','Himanso Sahni','jacobss2@mail.nih.gov','Anand Basu','basuan@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LSD - caIntegrator2','JP Marple','marplej@mail.nih.gov','Anand Basu','basuan@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LSD - CTODS','TBD','TBD','Christo Andonyadis','andonyac@mail.nih.gov');
INSERT INTO project_poc VALUES( 'LSD - NBIA','Jennifer Zeng','zengje@mail.nih.gov','Anand Basu','basuan@mail.nih.gov');
INSERT INTO project_poc VALUES( 'ProtExpress','Krishna Kanchinadam','kanchink@mail.nih.gov','Anand Basu','basuan@mail.nih.gov');
INSERT INTO project_poc VALUES( 'Rembrandt',' Himanso/Shine',' jacobss2@mail.nih.gov', 'Anand Basu' ,'basuan@mail.nih.gov');	  	  	  	  	 
INSERT INTO project_poc VALUES('TCGA - Project 1', 'Robert Sfeir', 'TBD', 'Carl Schaefer', 'cs339h@nih.gov');	  	 
INSERT INTO project_poc VALUES('TCGA - Project 2','Robert Sfeir', 'TBD',' Carl Schaefer','cs339h@nih.gov');