DROP TABLE MATURITY_MATRIX;

CREATE TABLE MATURITY_MATRIX (TOOL_NAME VARCHAR(30),PROJECT_STATUS VARCHAR(30));

INSERT INTO MATURITY_MATRIX VALUES('tool1', '(*)');
INSERT INTO MATURITY_MATRIX VALUES('tool2', '(*)');
INSERT INTO MATURITY_MATRIX VALUES('tool3', '(*r)');
INSERT INTO MATURITY_MATRIX VALUES('tool4', '(*b)');

SELECT * FROM MATURITY_MATRIX;